name: team_5_motionhack
description: 'GrowFundU'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.2.0
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  dio: ^5.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: '^0.13.1'

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icons/image.png'
  adaptive_icon_foreground: 'assets/icons/image.png'
  adaptive_icon_background: '#ffffff'

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/LogoMandiri.png
    - assets/LogoBCA.png
    - assets/LogoBNI.png
    - assets/LogoBRI.png
    - assets/LogoGopay.png
    - assets/LogoDana.png
    - assets/LogoLinkAja.png
    - assets/Banner.svg
    - assets/PPic.svg
    - assets/PPic.png
    - assets/BGBell.svg
    - assets/icons/konsultasi_icon.svg
    - assets/icons/Bell.svg
    - assets/icons/send_icon.svg
