name: team_5_motionhack
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/LogoMandiri.png
    - assets/LogoBCA.png
    - assets/LogoBNI.png
    - assets/LogoBRI.png
    - assets/LogoGopay.png
    - assets/LogoDana.png
    - assets/LogoLinkAja.png
    - assets/Banner.png
    - assets/icons/send_icon.svg
